#!/usr/bin/env node
// Compiles Vyper contracts via Ape and emits typed TypeScript ABIs plus a
// signatures.json snapshot that the runtime wrapper uses to surface drift.
//
// Modes:
//   node scripts/generate-abis.mjs            one-shot: compile + extract
//   node scripts/generate-abis.mjs --watch    initial run, then rerun on .vy change
//   node scripts/generate-abis.mjs --no-compile   skip `ape compile`, just re-extract

import { spawn, spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const FRONTEND = resolve(__dirname, '..')
const ROOT = resolve(FRONTEND, '..')
const MANIFEST = join(ROOT, '.build', '__local__.json')
const CONTRACTS_DIR = join(ROOT, 'contracts')
const OUT_DIR = join(FRONTEND, 'src', 'abis')

const args = new Set(process.argv.slice(2))
const WATCH = args.has('--watch')
const SKIP_COMPILE = args.has('--no-compile')

function log(msg) { process.stdout.write(`[abis] ${msg}\n`) }
function err(msg) { process.stderr.write(`[abis] ${msg}\n`) }

function resolveApe() {
  const local = join(ROOT, 'venv', 'bin', 'ape')
  if (existsSync(local)) return local
  return 'ape'
}

function apeCompile() {
  const ape = resolveApe()
  log(`compiling with ${ape}`)
  const r = spawnSync(ape, ['compile'], { cwd: ROOT, stdio: 'inherit' })
  if (r.status !== 0) throw new Error(`ape compile failed (exit ${r.status})`)
}

// --- ABI → signature helpers ---------------------------------------------

function formatInputs(inputs = []) {
  return inputs.map((i) => i.type).join(',')
}
function formatOutputs(outputs = []) {
  if (!outputs.length) return ''
  return ' -> ' + outputs.map((o) => o.type).join(',')
}
function signatureOf(entry) {
  if (entry.type === 'constructor') return `constructor(${formatInputs(entry.inputs)})`
  if (entry.type === 'event') return `event ${entry.name}(${formatInputs(entry.inputs)})`
  if (entry.type === 'function') return `${entry.name}(${formatInputs(entry.inputs)})${formatOutputs(entry.outputs)}`
  return `${entry.type}(${formatInputs(entry.inputs)})`
}
function signaturesFor(abi) {
  const fns = {}, events = {}
  for (const e of abi) {
    if (e.type === 'function') fns[e.name] = signatureOf(e)
    else if (e.type === 'event') events[e.name] = signatureOf(e)
  }
  return { functions: fns, events }
}

// --- Codegen -------------------------------------------------------------

function camel(name) {
  // Handle acronym prefixes: NFTGraphic -> nftGraphic (not nFTGraphic).
  // Count the leading run of uppercase letters. If it's 2+ and followed by a
  // lowercase letter, treat everything but the last uppercase as the acronym,
  // lowercase the acronym, and keep the rest unchanged.
  let i = 0
  while (i < name.length && /[A-Z]/.test(name[i])) i++
  if (i <= 1) return name[0].toLowerCase() + name.slice(1)
  if (i < name.length && /[a-z]/.test(name[i])) {
    return name.slice(0, i - 1).toLowerCase() + name.slice(i - 1)
  }
  return name.toLowerCase()
}

function extractBytecode(rawBytecode) {
  if (!rawBytecode) return '0x'
  if (typeof rawBytecode === 'string') return rawBytecode
  if (typeof rawBytecode === 'object' && typeof rawBytecode.bytecode === 'string') {
    return rawBytecode.bytecode
  }
  return '0x'
}

function renderAbiModule(contractName, abi, bytecode) {
  const varAbi = `${camel(contractName)}Abi`
  const varBc = `${camel(contractName)}Bytecode`
  return (
    `// AUTO-GENERATED by scripts/generate-abis.mjs — do not edit.\n` +
    `// Source: contracts/${contractName}.vy → .build/__local__.json\n\n` +
    `export const ${varAbi} = ${JSON.stringify(abi, null, 2)} as const\n` +
    `export type ${contractName}Abi = typeof ${varAbi}\n\n` +
    `export const ${varBc} = ${JSON.stringify(bytecode)} as \`0x\${string}\`\n`
  )
}

function renderIndex(contracts) {
  const imports = contracts
    .map((n) => `import { ${camel(n)}Abi, ${camel(n)}Bytecode } from './${n}'`)
    .join('\n')
  const entries = contracts
    .map(
      (n) =>
        `  ${n}: { abi: ${camel(n)}Abi, bytecode: ${camel(n)}Bytecode, signatures: signatures.${n} },`,
    )
    .join('\n')
  const reexports = contracts
    .map((n) => `export { ${camel(n)}Abi, ${camel(n)}Bytecode } from './${n}'`)
    .join('\n')
  return (
    `// AUTO-GENERATED by scripts/generate-abis.mjs — do not edit.\n\n` +
    `${imports}\n` +
    `import signatures from './signatures.json'\n\n` +
    `export const contracts = {\n${entries}\n} as const\n\n` +
    `export type ContractName = keyof typeof contracts\n\n` +
    `${reexports}\n`
  )
}

function extract() {
  if (!existsSync(MANIFEST)) {
    throw new Error(`manifest not found at ${MANIFEST} — did ape compile succeed?`)
  }
  const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8'))
  const types = manifest.contractTypes ?? {}
  const names = Object.keys(types).sort()
  if (!names.length) throw new Error('no contractTypes in manifest')

  mkdirSync(OUT_DIR, { recursive: true })

  const signatures = {}
  for (const name of names) {
    const abi = types[name].abi ?? []
    const bytecode = extractBytecode(types[name].deploymentBytecode)
    writeFileSync(join(OUT_DIR, `${name}.ts`), renderAbiModule(name, abi, bytecode))
    signatures[name] = signaturesFor(abi)
    log(`wrote src/abis/${name}.ts (${abi.length} entries, ${((bytecode.length - 2) / 2) | 0} bytes)`)
  }

  writeFileSync(
    join(OUT_DIR, 'signatures.json'),
    JSON.stringify(signatures, null, 2) + '\n',
  )
  writeFileSync(join(OUT_DIR, 'index.ts'), renderIndex(names))
  log(`wrote src/abis/index.ts + signatures.json (${names.length} contract(s))`)
}

function runOnce() {
  if (!SKIP_COMPILE) apeCompile()
  extract()
}

// --- Watch mode ----------------------------------------------------------

async function watch() {
  runOnce()
  const { watch: chokidarWatch } = await import('chokidar')
  log(`watching ${CONTRACTS_DIR}/**/*.vy`)
  const watcher = chokidarWatch(join(CONTRACTS_DIR, '**/*.vy'), { ignoreInitial: true })
  let queued = false, running = false
  const run = () => {
    if (running) { queued = true; return }
    running = true
    try { runOnce() } catch (e) { err(e.message) }
    running = false
    if (queued) { queued = false; run() }
  }
  watcher.on('add', run).on('change', run).on('unlink', run)
}

try {
  if (WATCH) await watch()
  else runOnce()
} catch (e) {
  err(e.stack ?? e.message)
  process.exit(1)
}
